//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CityLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReceiveDetails
    {
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SlNo { get; set; }
        public string InvestigationId { get; set; }
        public string PatientName { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
