//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CityLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSetup
    {
        public int SlNo { get; set; }
        public string VoucherNo { get; set; }
        public string PatientName { get; set; }
        public string Result { get; set; }
        public string Unites { get; set; }
        public string NormalValue { get; set; }
        public string PreparedBy { get; set; }
    }
}
